services:
  - type: web
    name: dark-shadow-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app_v5_final_backup.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DASHBOARD_PASS
        sync: false
      - key: RENDER_URL
        sync: false
    plan: free
